### ISSUE TITLE
When you decrement a value and it loses a digit, the caret become unattached to value

### ISSUE THREAD

**Issue by kizu** [LeaVerou/incrementable#3] opened 2012-01-02 22:07 UTC
Here is an example: You have the following situation (`|` — the caret):

```
background: linear-gradient(10deg|, #fed 50%, #fdc 50%);
```

If you'd decrement the value, `10` would become the `9` and the caret would become unattached to value:

```
background: linear-gradient(9deg,| #fed 50%, #fdc 50%);
```

This is bad, 'cause if you'd increment or decrement after that, the command won't work and you'd jump to the start/end of the input instead.

**Comment by LeaVerou** [comment] 2022-03-06 00:03
Cannot reproduce in v2, closing

**Closed by LeaVerou** 2022-03-06 00:03 UTC
